#!/bin/bash

# Tourism Management System Security Test Script
echo "🔐 Tourism Management System - Security Test Script"
echo "=================================================="

BASE_URL="http://localhost:8080/api"

echo ""
echo "📋 Test Cases:"
echo "1. User Registration"
echo "2. User Login"
echo "3. Access Protected Resource without Token"
echo "4. Access Protected Resource with Valid Token"
echo "5. Admin-only Endpoint Access"
echo "6. Role-based Access Control"

echo ""
echo "💡 To run these tests:"
echo "1. Start the application: mvn spring-boot:run"
echo "2. Use the following curl commands:"

echo ""
echo "🔹 1. Register a new tourist:"
echo "curl -X POST $BASE_URL/auth/register \\"
echo "  -H 'Content-Type: application/json' \\"
echo "  -d '{"
echo "    \"username\": \"john_tourist\","
echo "    \"email\": \"john@example.com\","
echo "    \"password\": \"password123\","
echo "    \"firstName\": \"John\","
echo "    \"lastName\": \"Doe\","
echo "    \"phone\": \"+1234567890\","
echo "    \"role\": \"TOURIST\""
echo "  }'"

echo ""
echo "🔹 2. Register an admin:"
echo "curl -X POST $BASE_URL/auth/register \\"
echo "  -H 'Content-Type: application/json' \\"
echo "  -d '{"
echo "    \"username\": \"admin_user\","
echo "    \"email\": \"admin@example.com\","
echo "    \"password\": \"admin123\","
echo "    \"firstName\": \"Admin\","
echo "    \"lastName\": \"User\","
echo "    \"phone\": \"+1234567891\","
echo "    \"role\": \"ADMIN\""
echo "  }'"

echo ""
echo "🔹 3. Login (save the token from response):"
echo "curl -X POST $BASE_URL/auth/login \\"
echo "  -H 'Content-Type: application/json' \\"
echo "  -d '{"
echo "    \"username\": \"john_tourist\","
echo "    \"password\": \"password123\""
echo "  }'"

echo ""
echo "🔹 4. Test unauthorized access:"
echo "curl -X GET $BASE_URL/v1/bookings"

echo ""
echo "🔹 5. Test authorized access (replace YOUR_JWT_TOKEN):"
echo "curl -X GET $BASE_URL/v1/bookings \\"
echo "  -H 'Authorization: Bearer YOUR_JWT_TOKEN'"

echo ""
echo "🔹 6. Test admin-only endpoint:"
echo "curl -X GET $BASE_URL/admin/users \\"
echo "  -H 'Authorization: Bearer YOUR_ADMIN_JWT_TOKEN'"

echo ""
echo "🔹 7. Get current user info:"
echo "curl -X GET $BASE_URL/auth/me \\"
echo "  -H 'Authorization: Bearer YOUR_JWT_TOKEN'"

echo ""
echo "🔹 8. Create a tour (requires ADMIN or TOUR_OPERATOR role):"
echo "curl -X POST $BASE_URL/v1/tours \\"
echo "  -H 'Content-Type: application/json' \\"
echo "  -H 'Authorization: Bearer YOUR_JWT_TOKEN' \\"
echo "  -d '{"
echo "    \"name\": \"Amazing Beach Tour\","
echo "    \"description\": \"A wonderful tour to the most beautiful beaches\","
echo "    \"destination\": \"Maldives\","
echo "    \"duration\": 7,"
echo "    \"maxParticipants\": 20,"
echo "    \"difficulty\": \"EASY\","
echo "    \"price\": 1500.00"
echo "  }'"

echo ""
echo "🔹 9. Public access to tours (no auth required):"
echo "curl -X GET $BASE_URL/v1/tours"

echo ""
echo "📊 Expected Responses:"
echo "- Registration/Login: 200/201 with JWT token"
echo "- Unauthorized access: 401 Unauthorized"
echo "- Authorized access: 200 with data"
echo "- Admin-only with tourist token: 403 Forbidden"
echo "- Admin-only with admin token: 200 with data"
echo "- Public endpoints: 200 with data (no auth needed)"

echo ""
echo "🚀 Start the application and test the security implementation!"
