server:
  port: 8082

spring:
  application:
    name: itinerary-service
  
  data:
    mongodb:
      host: localhost
      port: 27017
      database: tourism_itinerary_db
      # Remove authentication for local development
      # authentication-database: admin
      # username: ${MONGO_USERNAME:admin}
      # password: ${MONGO_PASSWORD:password}
  
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true
    hostname: localhost

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,circuitbreakers
  endpoint:
    health:
      show-details: always

logging:
  level:
    com.tourism: DEBUG
    org.springframework.data.mongodb: DEBUG
    org.springframework.security: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

# Circuit Breaker Configuration
resilience4j:
  circuitbreaker:
    instances:
      tour-service:
        registerHealthIndicator: true
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 5s
        failureRateThreshold: 50
        eventConsumerBufferSize: 10
  
  retry:
    instances:
      tour-service:
        maxAttempts: 3
        waitDuration: 2s

# Feign Configuration
feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
  circuitbreaker:
    enabled: true

# OpenAPI Documentation
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
